name: Continuous Deployment
on:
  push:
    branches: [main, 'release/**']

permissions:
  id-token: write
  issues: write
  contents: write
  pull-requests: write

jobs:
  resolve-version:
    uses: 2060-io/organization/.github/workflows/resolve-version-call.yml@main
    with:
      bump-minor-pre-major: false

  release:
    needs: [resolve-version]
    if: needs.resolve-version.outputs.new-release-published == 'true'
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ${{ needs.resolve-version.outputs.release-version }}
      RELEASE_TYPE: ${{ needs.resolve-version.outputs.release-type }}
    steps:

      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Corepack pnpm
        # OIDC publishing requires a very up to date npm version
        run: |
          npm install -g npm@latest
          corepack enable

      - run: pnpm install --frozen-lockfile
      - run: pnpm version "$RELEASE_VERSION"

      - name: Publish to npm
        run: |
          if [ "$RELEASE_TYPE" = "stable" ]; then
            pnpm publish --no-git-checks --access public
          else
            pnpm publish --no-git-checks --access public --tag dev
          fi


