name: Continuous Deployment
on:
  push:
    branches: [main, 'release/**']

permissions:
  id-token: write
  issues: write
  contents: write
  pull-requests: write

jobs:
  resolve-version:
    uses: 2060-io/organization/.github/workflows/resolve-version-call.yml@5f813454d8962db006c4e4466f3af1cf4af8dfa4 # main
    with:
      bump-minor-pre-major: false

  release:
    needs: [resolve-version]
    if: needs.resolve-version.outputs.new-release-published == 'true'
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ${{ needs.resolve-version.outputs.release-version }}
      RELEASE_TYPE: ${{ needs.resolve-version.outputs.release-type }}
    steps:

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '22.14.0'
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - name: Corepack pnpm
        # OIDC publishing requires a very up to date npm version
        run: |
          npm install -g npm@11.11.0
          corepack enable

      - run: pnpm install --frozen-lockfile
      - run: pnpm version "$RELEASE_VERSION" --no-git-tag-version --allow-same-version

      - name: Publish to npm
        run: |
          if [ "$RELEASE_TYPE" = "stable" ]; then
            pnpm publish --no-git-checks --access public
          else
            pnpm publish --no-git-checks --access public --tag dev
          fi


