name: Continuous Deployment
on:
  push:
    branches: [main, 'release/**']

permissions:
  id-token: write
  issues: write
  contents: write
  pull-requests: write

jobs:
  resolve-version:
    uses: 2060-io/organization/.github/workflows/resolve-version-call.yml@625c6d0b6ba22b9c429d42bdeb57d506853456dc # main
    with:
      bump-minor-pre-major: false

  release:
    needs: [resolve-version]
    if: needs.resolve-version.outputs.new-release-published == 'true'
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ${{ needs.resolve-version.outputs.release-version }}
      RELEASE_TYPE: ${{ needs.resolve-version.outputs.release-type }}
    steps:

      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: '24'
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - name: Corepack pnpm
        # OIDC publishing requires a very up to date npm version
        run: |
          npm install -g npm@11.11.0
          corepack enable

      - run: pnpm install --frozen-lockfile
      - run: pnpm version "$RELEASE_VERSION" --no-git-tag-version --allow-same-version

      - name: Publish to npm
        run: |
          if [ "$RELEASE_TYPE" = "stable" ]; then
            pnpm publish --no-git-checks --access public
          else
            pnpm publish --no-git-checks --access public --tag dev
          fi


